-- =====================================================================
-- Coimbrões Youth Cup 2026 — schema Supabase (Postgres)
-- Espelha exatamente a forma dos dados em js/data.js, para o front-end
-- só precisar de trocar os imports locais por:
--   supabase.from('equipas').select('*')
--   supabase.from('jogos').select('*')
--   supabase.from('jogadores').select('*')
--   supabase.from('patrocinadores').select('*')
--
-- Corre este ficheiro inteiro no SQL Editor do Supabase (Project ->
-- SQL Editor -> New query -> colar -> Run).
-- =====================================================================


-- =====================================================================
-- 1. TABELAS DE REFERÊNCIA (substituem FASE_LABEL / CAMPO_LABEL / duracaoJogo)
-- =====================================================================

create table if not exists fases (
    code        text primary key,                 -- 'grupo_a', 'liga_campeoes', ...
    label       text not null,                     -- 'Grupo A', 'Liga Campeões', ...
    tipo        text not null check (tipo in ('grupo', 'final')),
    duracao_min smallint not null
);

comment on table fases is 'Equivalente a FASE_LABEL + duracaoJogo() em data.js.';

insert into fases (code, label, tipo, duracao_min) values
    ('grupo_a',          'Grupo A',            'grupo', 30),
    ('grupo_b',          'Grupo B',            'grupo', 30),
    ('grupo_c',          'Grupo C',            'grupo', 30),
    ('liga_campeoes',    'Liga Campeões',      'final', 40),
    ('liga_europa',      'Liga Europa',        'final', 40),
    ('liga_conferencia', 'Liga Conferência',   'final', 40)
on conflict (code) do nothing;


create table if not exists campos (
    numero smallint primary key,   -- 1, 2
    nome   text not null           -- 'Campo Clínica RIR', 'Campo PRINT&CUT'
);

comment on table campos is 'Equivalente a CAMPO_LABEL em data.js. Muda aqui o nome se trocares de patrocinador do campo.';

insert into campos (numero, nome) values
    (1, 'Campo Clínica RIR'),
    (2, 'Campo PRINT&CUT')
on conflict (numero) do nothing;


create table if not exists tiers_patrocinador (
    code  text primary key,     -- 'ouro', 'prata', 'bronze'
    label text not null,        -- título mostrado na aba Patrocinadores
    ordem smallint not null     -- ordem de exibição das secções
);

comment on table tiers_patrocinador is 'Equivalente a TIER_LABEL / TIER_ORDER em data.js.';

insert into tiers_patrocinador (code, label, ordem) values
    ('ouro', 'Patrocinadores', 1)
on conflict (code) do nothing;
-- Se um dia tiveres patrocinadores de outro nível, acrescenta aqui:
-- insert into tiers_patrocinador (code, label, ordem) values ('prata', 'Apoios', 2);


-- =====================================================================
-- 2. EQUIPAS
-- =====================================================================

create table if not exists equipas (
    id         bigint generated by default as identity primary key,
    nome       text not null,
    escudo_url text,                                   -- link público no Storage (bucket "escudos")
    iniciais   text not null,                           -- fallback se a imagem falhar
    grupo      char(1) not null check (grupo in ('A', 'B', 'C')),
    created_at timestamptz not null default now()
);

comment on table equipas is 'Equivalente a EQUIPAS em data.js.';
comment on column equipas.escudo_url is 'Ex: https://<projeto>.supabase.co/storage/v1/object/public/escudos/scc.png';

insert into equipas (id, nome, escudo_url, iniciais, grupo) overriding system value values
    (1, 'SC Coimbrões A', 'assets/equipas/coimbroes.png', 'SCC-1', 'A'),
    (2, 'FC Porto',        'assets/equipas/porto.png',     'FCP',   'A'),
    (3, 'Leixões SC',      'assets/equipas/leixoes.png',   'LSC',   'A'),
    (4, 'SC Coimbrões B', 'assets/equipas/coimbroes.png', 'SCC-2', 'B'),
    (5, 'SC Braga',        'assets/equipas/braga.png',     'SCB',   'B'),
    (6, 'CF Perosinho',    'assets/equipas/perosinho.png', 'CFP',   'B'),
    (7, 'SC Coimbrões C', 'assets/equipas/coimbroes.png', 'SCC-3', 'C'),
    (8, 'SC Espinho',      'assets/equipas/espinho.png',   'SCE',   'C'),
    (9, 'SC Salgueiros',   'assets/equipas/salgueiros.png','SCS',   'C')
on conflict (id) do nothing;


-- =====================================================================
-- 3. JOGOS
-- =====================================================================

create table if not exists jogos (
    id               bigint generated by default as identity primary key,
    fase             text not null references fases(code),
    campo            smallint not null references campos(numero),
    hora             time not null,

    -- Jogos de grupo: equipa_casa_id/equipa_fora_id preenchidos (id direto).
    equipa_casa_id   bigint references equipas(id),
    equipa_fora_id   bigint references equipas(id),

    -- Jogos da fase final, ANTES de o grupo respetivo terminar: em vez de
    -- um id direto, guarda-se a "seed" (posição no grupo). Equivalente a
    -- { grupo: "A", posicao: 1 } em data.js — resolvido em runtime pela
    -- mesma lógica de resolverSeed()/resolverEquipaJogo() em stats.js.
    seed_casa_grupo    char(1) check (seed_casa_grupo in ('A', 'B', 'C')),
    seed_casa_posicao  smallint check (seed_casa_posicao between 1 and 3),
    seed_fora_grupo    char(1) check (seed_fora_grupo in ('A', 'B', 'C')),
    seed_fora_posicao  smallint check (seed_fora_posicao between 1 and 3),

    golos_casa       smallint,
    golos_fora       smallint,
    estado           text not null default 'agendado'
                       check (estado in ('agendado', 'a_decorrer', 'terminado')),
    minuto           smallint,   -- minuto ao vivo, só relevante quando estado = 'a_decorrer'

    created_at       timestamptz not null default now(),
    updated_at       timestamptz not null default now(),

    -- Cada lado tem de vir preenchido de UMA forma só: id direto OU seed,
    -- nunca as duas nem nenhuma.
    constraint jogos_lado_casa_valido check (
        (equipa_casa_id is not null and seed_casa_grupo is null and seed_casa_posicao is null)
        or
        (equipa_casa_id is null and seed_casa_grupo is not null and seed_casa_posicao is not null)
    ),
    constraint jogos_lado_fora_valido check (
        (equipa_fora_id is not null and seed_fora_grupo is null and seed_fora_posicao is null)
        or
        (equipa_fora_id is null and seed_fora_grupo is not null and seed_fora_posicao is not null)
    )
);

comment on table jogos is 'Equivalente a JOGOS em data.js.';

create index if not exists idx_jogos_fase   on jogos (fase);
create index if not exists idx_jogos_estado on jogos (estado);

-- Mantém updated_at sempre correto sem teres de o definir à mão em cada UPDATE.
create or replace function set_updated_at()
returns trigger as $$
begin
    new.updated_at = now();
    return new;
end;
$$ language plpgsql;

drop trigger if exists trg_jogos_updated_at on jogos;
create trigger trg_jogos_updated_at
    before update on jogos
    for each row execute function set_updated_at();

-- ---- Fase de grupos (manhã) — round-robin de 3 equipas por grupo ----
insert into jogos (id, fase, campo, hora, equipa_casa_id, equipa_fora_id, estado) overriding system value values
    (1, 'grupo_a', 1, '09:00', 1, 3, 'agendado'),
    (2, 'grupo_b', 2, '09:00', 4, 6, 'agendado'),
    (3, 'grupo_a', 2, '09:40', 1, 2, 'agendado'),
    (4, 'grupo_c', 1, '09:40', 7, 9, 'agendado'),
    (5, 'grupo_b', 1, '10:20', 4, 5, 'agendado'),
    (6, 'grupo_c', 2, '10:20', 7, 8, 'agendado'),
    (7, 'grupo_a', 1, '11:00', 2, 3, 'agendado'),
    (8, 'grupo_b', 2, '11:00', 5, 6, 'agendado'),
    (9, 'grupo_c', 1, '11:40', 8, 9, 'agendado')
on conflict (id) do nothing;

-- ---- Fase final (tarde) — equipas ainda por decidir (seeds) ----
insert into jogos (
    id, fase, campo, hora,
    seed_casa_grupo, seed_casa_posicao,
    seed_fora_grupo, seed_fora_posicao,
    estado
) overriding system value values
    (10, 'liga_conferencia', 1, '14:00', 'A', 3, 'B', 3, 'agendado'),
    (11, 'liga_europa',      2, '14:00', 'A', 2, 'B', 2, 'agendado'),
    (12, 'liga_campeoes',    1, '14:50', 'A', 1, 'B', 1, 'agendado'),
    (13, 'liga_conferencia', 2, '14:50', 'B', 3, 'C', 3, 'agendado'),
    (14, 'liga_europa',      1, '15:40', 'B', 2, 'C', 2, 'agendado'),
    (15, 'liga_campeoes',    2, '15:40', 'B', 1, 'C', 1, 'agendado'),
    (16, 'liga_conferencia', 1, '16:30', 'A', 3, 'C', 3, 'agendado'),
    (17, 'liga_europa',      2, '16:30', 'A', 2, 'C', 2, 'agendado'),
    (18, 'liga_campeoes',    1, '17:20', 'A', 1, 'C', 1, 'agendado')
on conflict (id) do nothing;


-- =====================================================================
-- 4. JOGADORES
-- =====================================================================

create table if not exists jogadores (
    id         bigint generated by default as identity primary key,
    equipa_id  bigint not null references equipas(id) on delete cascade,
    numero     smallint not null,
    nome       text not null,
    created_at timestamptz not null default now(),
    unique (equipa_id, numero)   -- duas camisolas iguais na mesma equipa não fazem sentido
);

comment on table jogadores is
    'Equivalente a JOGADORES em data.js. Nomes ainda são placeholders '
    '("Jogador N") — substitui pelos nomes reais só depois de teres '
    'autorização dos encarregados de educação (dados de menores, sub-10).';

-- Gera os mesmos 10 jogadores-placeholder por equipa que gerarPlantelPlaceholder()
-- fazia em JS, com o mesmo esquema de id (equipa_id * 100 + numero).
insert into jogadores (id, equipa_id, numero, nome)
select
    e.id * 100 + n as id,
    e.id           as equipa_id,
    n              as numero,
    'Jogador ' || n as nome
from equipas e
cross join generate_series(1, 10) as n
on conflict (id) do nothing;


-- =====================================================================
-- 5. PATROCINADORES
-- =====================================================================

create table if not exists patrocinadores (
    id         bigint generated by default as identity primary key,
    nome       text not null,
    tier       text not null references tiers_patrocinador(code),
    logo_url   text,
    created_at timestamptz not null default now()
);

comment on table patrocinadores is 'Equivalente a PATROCINADORES em data.js.';

insert into patrocinadores (id, nome, tier, logo_url) overriding system value values
    (1, 'Clínica RIR', 'ouro', 'assets/patrocinadores/clinica-rir.png'),
    (2, 'PRINT&CUT',   'ouro', 'assets/patrocinadores/print-cut.jpg'),
    (3, 'Decathlon',   'ouro', 'assets/patrocinadores/decathlon.png')
on conflict (id) do nothing;


-- =====================================================================
-- 6. Sincronizar as sequências das identity columns
-- Como inserimos ids explícitos acima (overriding system value), as
-- sequências internas ainda não sabem que esses números já estão
-- ocupados. Isto garante que o próximo INSERT sem id explícito continua
-- a partir do valor certo, em vez de tentar repetir o id 1.
-- =====================================================================

select setval(pg_get_serial_sequence('equipas', 'id'),       (select max(id) from equipas));
select setval(pg_get_serial_sequence('jogos', 'id'),         (select max(id) from jogos));
select setval(pg_get_serial_sequence('jogadores', 'id'),     (select max(id) from jogadores));
select setval(pg_get_serial_sequence('patrocinadores', 'id'),(select max(id) from patrocinadores));


-- =====================================================================
-- 7. ROW LEVEL SECURITY
-- Leitura pública (o site é público), escrita fechada por agora — só o
-- service_role (usado no backend/admin, nunca no browser) pode escrever.
-- Quando tiveres um painel de admin com login, troca a policy de escrita
-- para `to authenticated` com a condição que fizer sentido.
-- =====================================================================

alter table fases               enable row level security;
alter table campos               enable row level security;
alter table tiers_patrocinador   enable row level security;
alter table equipas              enable row level security;
alter table jogos                enable row level security;
alter table jogadores            enable row level security;
alter table patrocinadores       enable row level security;

create policy "leitura publica" on fases               for select using (true);
create policy "leitura publica" on campos               for select using (true);
create policy "leitura publica" on tiers_patrocinador   for select using (true);
create policy "leitura publica" on equipas              for select using (true);
create policy "leitura publica" on jogos                for select using (true);
create policy "leitura publica" on jogadores            for select using (true);
create policy "leitura publica" on patrocinadores       for select using (true);

-- Exemplo (comentado) de como abrir a escrita a utilizadores autenticados
-- mais tarde, quando existir um login de organização:
-- create policy "staff pode atualizar jogos" on jogos
--     for update to authenticated using (true) with check (true);

create policy "staff pode atualizar jogos" on jogos
    for update to authenticated using (true) with check (true);